name: Deploy Backend & Frontend

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          echo "Starting backend deployment..."
          curl -X POST "https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"
          echo "Backend deploy triggered successfully."

  wait_backend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Wait for Render backend to be live
        run: |
          echo "Waiting for backend to become available..."
          for i in {1..30}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://smartleads-ai-crm.onrender.com/health || true)
            if [ "$STATUS" = "200" ]; then
              echo "Backend is live!"
              exit 0
            fi
            echo "Backend not ready yet (status: $STATUS). Retrying in 10s..."
            sleep 10
          done
          echo "Backend failed to become ready in time."
          exit 1

  frontend:
    runs-on: ubuntu-latest
    needs: wait_backend
    steps:
      - name: Trigger Vercel Deploy
        run: |
          echo "Starting frontend deployment..."
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
          echo "Frontend deploy triggered successfully."
